### ISSUE TITLE
Not in npm registry

### ISSUE THREAD

**Issue by charltoons** [secrettriangle/rolex#2]
This repo is not in the npmjs.org registry, so `npm install packemaker` does not work. Consider publishing to npm and updating your README with the new package name.

**Comment by secrettriangle** [comment]
@charltoons you are right! I will have to change the name in `package.json` since there's already a package called pacemaker. In the meantime, you can use this by adding `"pacemaker": "secrettriangle/pacemaker"` to your `dependencies`.

**Comment by secrettriangle** [comment]
@charltoons I've updated the package -- you can now `npm install rolex`. Closing.
